services:
  proxy:
    build: .
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
      - api
    volumes:
      - ./nginx.prod.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    networks:
      - app-network
    restart: unless-stopped
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - app-network
    depends_on:
      - proxy
    restart: unless-stopped
    command: >
      sh -c "
        apk add --no-cache dcron &&
        echo '0 12 * * 0 /usr/local/bin/certbot renew --quiet --deploy-hook \"docker exec domi-proxy-1 nginx -s reload\"' > /etc/crontabs/root &&
        crond -f -d 8
      "

  web:
    build: ./packages/web
    networks:
      - app-network
    restart: unless-stopped

  api:
    build: ./packages/api
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
