services:
  proxy:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - web
      - api
    networks:
      - app-network

  web:
    build: ./packages/web
    networks:
      - app-network

  api:
    build: ./packages/api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
