#:schema node_modules/wrangler/config-schema.json
name = "domi"
main = ".worker-next/index.mjs"
compatibility_date = "2024-09-26"
compatibility_flags = ["nodejs_compat"]

# keep bundle size down, improve startup time
minify = true

# hosts the static frontend files
assets = { directory = ".worker-next/assets", binding = "ASSETS" }

# setup variables
vars = { ENVIORNMENT = "development" }

# custom domain config
routes = [{ pattern = "dev.usedomi.com", custom_domain = true }]

[env.production]
vars = { ENVIORNMENT = "production" }
routes = [{ pattern = "usedomi.com", custom_domain = true }]