name = "domi"
main = ".worker-next/index.mjs"

compatibility_date = "2024-09-26"
compatibility_flags = ["nodejs_compat"]

# manage size of worker
minify = true

# create binding for static assets
assets = { directory = ".worker-next/assets", binding = "ASSETS" }

# set custom domain
routes = [
  { pattern = "usedomi.com", custom_domain = true }
]

# enable workers logs
[observability]
enabled = true